-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 15:09:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Elective
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Elective
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Elective` DEFAULT CHARACTER SET utf8 ;
USE `Elective` ;

-- -----------------------------------------------------
-- Table `Elective`.`enrollee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`enrollee` (
  `enrollee_id` INT NOT NULL AUTO_INCREMENT,
  `role` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `faculity` INT NOT NULL,
  `privilege` INT NULL,
  INDEX `fk_enrollee_faculity1_idx` (`faculity` ASC) VISIBLE,
  INDEX `fk_enrollee_role1_idx` (`role` ASC) VISIBLE,
  PRIMARY KEY (`enrollee_id`),
  UNIQUE INDEX `enrollee_id_UNIQUE` (`enrollee_id` ASC) VISIBLE,
  INDEX `privelege_idx` (`privilege` ASC) VISIBLE,
  CONSTRAINT `fk_enrollee_faculity1`
    FOREIGN KEY (`faculity`)
    REFERENCES `Elective`.`faculity` (`faculity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollee_role1`
    FOREIGN KEY (`role`)
    REFERENCES `Elective`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `privelege`
    FOREIGN KEY (`privilege`)
    REFERENCES `Elective`.`privelege` (`privelege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Elective`.`faculity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`faculity` (
  `faculity_id` INT NOT NULL AUTO_INCREMENT,
  `faculity_name` VARCHAR(45) NOT NULL,
  `free_aducation_plan` INT NOT NULL DEFAULT 0,
  `min_passing_score` INT NULL,
  PRIMARY KEY (`faculity_id`),
  UNIQUE INDEX `faculity_id_UNIQUE` (`faculity_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`faculity_name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Elective`.`gradereport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`gradereport` (
  `gradereport_id` INT NOT NULL AUTO_INCREMENT,
  `enrollee_id` INT NOT NULL,
  `attestat` DECIMAL(1,1) NOT NULL,
  `isAccepted` TINYINT(1) NULL,
  `isFree` TINYINT(1) NULL,
  PRIMARY KEY (`gradereport_id`),
  UNIQUE INDEX `gradereport_id_UNIQUE` (`gradereport_id` ASC) VISIBLE,
  INDEX `enrollee_id_idx` (`enrollee_id` ASC) VISIBLE,
  CONSTRAINT `enrollee_id`
    FOREIGN KEY (`enrollee_id`)
    REFERENCES `Elective`.`enrollee` (`enrollee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Elective`.`gradereport2subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`gradereport2subject` (
  `gradereport_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `mark` INT NOT NULL,
  INDEX `gradereport_id_idx` (`gradereport_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `gradereport_id`
    FOREIGN KEY (`gradereport_id`)
    REFERENCES `Elective`.`gradereport` (`gradereport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Elective`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Elective`.`privelege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`privelege` (
  `privelege_id` INT NOT NULL AUTO_INCREMENT,
  `privelege` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`privelege_id`),
  UNIQUE INDEX `privelege_id_UNIQUE` (`privelege_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Elective`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Elective`.`subject2faculity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`subject2faculity` (
  `faculity_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  INDEX `faculity_id_idx` (`faculity_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `faculity_id`
    FOREIGN KEY (`faculity_id`)
    REFERENCES `Elective`.`faculity` (`faculity_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Elective`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Elective`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`subject_id`),
  UNIQUE INDEX `id_UNIQUE` (`subject_id` ASC) VISIBLE,
  UNIQUE INDEX `subject_name_UNIQUE` (`subject_name` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
