-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 15:01:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Elective
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Elective
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Elective` DEFAULT CHARACTER SET utf8 ;
USE `Elective` ;

-- -----------------------------------------------------
-- Table `Elective`.`faculity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`faculity` (
  `faculity_id` INT NOT NULL AUTO_INCREMENT,
  `faculity_name` VARCHAR(45) NOT NULL,
  `free_aducation_plan` INT NOT NULL DEFAULT 0,
  `paid_aducation_plan` INT NULL,
  PRIMARY KEY (`faculity_id`));

CREATE UNIQUE INDEX `faculity_id_UNIQUE` ON `Elective`.`faculity` (`faculity_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `title_UNIQUE` ON `Elective`.`faculity` (`faculity_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`gradereport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`gradereport` (
  `gradereport_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enrollee_id` INT NOT NULL,
  `attestat` DECIMAL(1,1) NOT NULL,
  `isAccepted` TINYINT(1) NULL,
  `isFree` TINYINT(1) NULL,
  PRIMARY KEY (`gradereport_id`),
  CONSTRAINT `enrollee_id`
    FOREIGN KEY (`enrollee_id`)
    REFERENCES `Elective`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `enrollee_id_idx` ON `Elective`.`gradereport` (`enrollee_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`gradereport2subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`gradereport2subject` (
  `gradereport_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `mark` INT NOT NULL,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Elective`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gradereport_id`
    FOREIGN KEY (`gradereport_id`)
    REFERENCES `Elective`.`gradereport` (`enrollee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `subject_id_idx` ON `Elective`.`gradereport2subject` (`subject_id` ASC) VISIBLE;

CREATE INDEX `gradereport_id_idx` ON `Elective`.`gradereport2subject` (`gradereport_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`privelege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`privelege` (
  `privelege_id` INT NOT NULL AUTO_INCREMENT,
  `privelege` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`privelege_id`));

CREATE UNIQUE INDEX `privelege_id_UNIQUE` ON `Elective`.`privelege` (`privelege_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`));

CREATE UNIQUE INDEX `category_id_UNIQUE` ON `Elective`.`role` (`role_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `role_UNIQUE` ON `Elective`.`role` (`role` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`subject2faculity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`subject2faculity` (
  `faculity_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `priority` INT NULL,
  CONSTRAINT `faculity_id`
    FOREIGN KEY (`faculity_id`)
    REFERENCES `Elective`.`faculity` (`faculity_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Elective`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `faculity_id_idx` ON `Elective`.`subject2faculity` (`faculity_id` ASC) VISIBLE;

CREATE INDEX `subject_id_idx` ON `Elective`.`subject2faculity` (`subject_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`subject_id`));

CREATE UNIQUE INDEX `id_UNIQUE` ON `Elective`.`subjects` (`subject_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `subject_name_UNIQUE` ON `Elective`.`subjects` (`subject_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `role` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `pasword` VARCHAR(45) NOT NULL,
  `privilege` INT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_enrollee_role1`
    FOREIGN KEY (`role`)
    REFERENCES `Elective`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `privelege`
    FOREIGN KEY (`privilege`)
    REFERENCES `Elective`.`privelege` (`privelege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_enrollee_role1_idx` ON `Elective`.`user` (`role` ASC) VISIBLE;

CREATE UNIQUE INDEX `enrollee_id_UNIQUE` ON `Elective`.`user` (`user_id` ASC) VISIBLE;

CREATE INDEX `privelege_idx` ON `Elective`.`user` (`privilege` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Elective`.`user2faculity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Elective`.`user2faculity` (
  `user_id` INT NOT NULL,
  `faculity_id` INT NOT NULL,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Elective`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `faculity_id `
    FOREIGN KEY (`faculity_id`)
    REFERENCES `Elective`.`faculity` (`faculity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `user_id_idx` ON `Elective`.`user2faculity` (`user_id` ASC) VISIBLE;

CREATE INDEX `faculity_id _idx` ON `Elective`.`user2faculity` (`faculity_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;